apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads
  namespace: amazona
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: amazona
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        #image: us.gcr.io/testkubernetes-01/react-front
        image: frontapp
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-front
  namespace: amazona
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer