apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: amazona
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: amazona
  labels:
    tipo: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      tipo: mongo
  template:
    metadata:
      labels:
        tipo: mongo 
    spec:
      containers:
      - name: mongo
        image: mongo                        
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: vol
            mountPath: /data/db
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-mongo
  namespace: amazona
spec:
  selector:
    tipo: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP