apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads
  namespace: amazona
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: amazona
  labels:
    tipo: back
spec:
  replicas: 1
  selector:
    matchLabels:
      tipo: back
  template:
    metadata:
      labels:
        tipo: back 
    spec:
      containers:
      - name: back
        image: us.gcr.io/testkubernetes-01/back
        #image: backapp
        imagePullPolicy: Never
        env:
          - name: MONGODB_URL_LOCAL
            value: "mongodb://mi-servicio-mongo.amazona.svc.cluster.local:27017"
          - name: JWT_SECRET
            value: "secretJWT12345"                           
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: vol
            mountPath: /usr/src/app/uploads
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-uploads

---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-back
  namespace: amazona
spec:
  selector:
    tipo: back
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP